<?php
return array (
  'autogenerated-15-9bf31c7ff062936a96d3c8bd1f8f2ff3' => 
  array (
    'base' => 'http://localhost/typo3extension/',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 15,
    'websiteTitle' => '',
  ),
  'autogenerated-18-6f4922f45568161a8cdf4ad2299f6d23' => 
  array (
    'base' => 'http://localhost/typo3extension',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 18,
    'websiteTitle' => '',
  ),
  'autogenerated-6-1679091c5a880faf6fb5e6087eb1b2dc' => 
  array (
    'base' => 'http://localhost/typo3extension/pocetna',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 6,
    'websiteTitle' => '',
  ),
);
#